name: Algolia Crawler
on:
  push:
    branches: [master]  # main 브랜치에 push될 때마다 실행

jobs:
  algolia_crawler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Get the content of algolia.config.json as config
        id: algolia_config
        run: echo "config=$(cat algolia.config.json | jq -r tostring)" >> $GITHUB_OUTPUT
      
      - name: Run Algolia Crawler
        uses: signcl/docsearch-scraper-action@master
        env:
          APPLICATION_ID: ${{ secrets.ALGOLIA_APP_ID }}
          API_KEY: ${{ secrets.ALGOLIA_WRITE_API_KEY }}
          CONFIG: ${{ steps.algolia_config.outputs.config }}